frontend/package-lock.json
package-lock said it was modified so I pushed it up.
=> package-lock modification

frontend/src/components/users/LoginUser.jsx
=> fixe inputs

db/package-lock.json, frontend/src/components/App.css, frontend/src/components/App.js, frontend/src/components/LoggedInUser/profile.js
added .topbar css for profile page
=> added topbar

backend/db/queries.js
Registering users now takes: email, password, username, full name
=> completed login and register queries

frontend/src/components/LoggedInUser/SinglePhoto.jsx
Created SinglePhoto component to grab photo, photo url, users who liked the photo
=> Single photo

frontend/src/components/LoggedInUser/User_Info.js
=> added user info sfc

frontend/package.json, frontend/public/index.html, frontend/src/components/App.css, frontend/src/components/App.js
finished the design for the top bar of the profile page
=> Topbarstyle

frontend/src/components/LoggedInUser/SinglePhoto.jsx
Changed nothing except for commenting out all the functions
=> commented out functions for testing

frontend/src/components/App.js, frontend/src/components/LoggedInUser/profile.js, frontend/src/components/LoggedInUser/profileImages.jsx
changed around some component props
=> changed around some component props

frontend/src/components/App.css, frontend/src/components/users/LoginUser.jsx
did the styling for the login page.  pending images for app store/google play
=> login page layout

frontend/src/components/App.js, frontend/src/components/LoggedInUser/Followers.jsx, frontend/src/components/LoggedInUser/Following.jsx, frontend/src/components/LoggedInUser/Home.jsx, frontend/src/components/LoggedInUser/SinglePhoto.jsx, frontend/src/components/LoggedInUser/User.jsx, frontend/src/components/LoggedInUser/profile.js, frontend/src/components/LoggedInUser/profileImages.jsx, frontend/src/components/users/LoginUser.jsx
Created new components 
Rearranged routes 
Changed login redirect from /profile to /home
=> Helen routes

frontend/src/components/App.css, frontend/src/components/users/LoginUser.jsx
added app store and google play
=> add app store

frontend/src/components/users/LoginUser.jsx
=> Stylingpages

frontend/src/components/App.css, frontend/src/components/users/LoginUser.jsx, frontend/src/components/users/NewUserMain.jsx
=> styling for registering user

frontend/src/components/App.css, frontend/src/components/App.js, frontend/src/components/users/LoginUser.jsx, frontend/src/components/users/NewUserMain.jsx
removed text decoration for sign up and login.  kindly check top bar left camera icon and instagram link if working.  did not remove text-decoration for instagram yet.
=> removed text decoration

frontend/src/components/LoggedInUser/Home.jsx
Grabbing photo feed information based on follower information
=> Working on rendering based on photoFeed

frontend/src/components/App.css, frontend/src/components/LoggedInUser/User.jsx, frontend/src/components/LoggedInUser/UserInfo.js, frontend/src/components/LoggedInUser/profile.js
The profile css isnt done yet. But im giving what i have so far and I plan on finishing it today...stand by. I touched App.css at the bottom to add styling
=> added the profile image and some styling for the profile to app.css

backend/db/queries.js
new route localhost:3001/users/u/:id/edit
=> added the edit router route SHOUTS TO HELEN

backend/db/queries.js, frontend/src/components/LoggedInUser/EditUser.jsx, frontend/src/components/LoggedInUser/User.jsx
added the number of liked photos query
=> added the number of liked photos query

backend/db/queries.js, backend/routes/users.js, frontend/src/components/LoggedInUser/Home.jsx
Added query to grab total likes per photo
=> Helen homefeed

frontend/src/components/Followers.css, frontend/src/components/LoggedInUser/Followers.jsx
waiting for the component to be finished to continue
=> initial styling for followers

frontend/src/components/Home.css, frontend/src/components/LoggedInUser/Home.jsx
Renders full heart or empty heart depending on if the photo is liked by user.
=> Add hearts

backend/routes/users.js, frontend/src/components/LoggedInUser/EditUser.jsx, frontend/src/components/LoggedInUser/User.jsx, frontend/src/components/LoggedInUser/UserInfo.js
can now edit a user. Clicking a profile picture takes you to an edit page.
=> can now edit a user :)

backend/db/instaclone.sql
=> Add more images and users to db

backend/db/instaclone.sql, frontend/src/components/LoggedInUser/Followers.jsx, frontend/src/components/LoggedInUser/Following.jsx
fixed a bug with showing the followers and followings profile
=> finished the followers and following

frontend/src/components/Followers.css, frontend/src/components/LoggedInUser/Followers.jsx
changed image size, username and fullname
=> added some classNames

frontend/src/components/LoggedInUser/EditUser.jsx
guys test and make sure its lit!
=> may be fully able to edit a user now

frontend/src/components/LoggedInUser/profile.css
Delete temporary background color
=> Actually finish responsive grid

frontend/src/components/App.css, frontend/src/components/LoggedInUser/UserInfo.js, frontend/src/components/LoggedInUser/profile.css, frontend/src/components/LoggedInUser/profileImages.jsx
Move part of styling from App.css to Profile.css to keep it under one file 
Commented out some divs under UserInfo 
Responsive flexbox for user info div
=> Responsive styling for profile user information

backend/db/queries.js
Query to add user id and photo id to likes table
=> Add user likes query

frontend/src/components/App.css, frontend/src/components/LoggedInUser/EditUser.jsx
=> restyled our edit user

frontend/src/components/App.css, frontend/src/components/LoggedInUser/EditUser.jsx
=> fixed styling
